Update ./run script to latest version (#2710)
* Update ./run script to latest version

* Update Travis config with correct versions of node and bundler

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,7 +1,7 @@
 #! /usr/bin/env bash
 
 # CAUTION:
-# This file was generated by generator-canonical-webteam@3.4.1
+# This file was generated by generator-canonical-webteam@3.4.2
 # and should usually not be edited directly.
 #
 # This file was generated by the "canonical-webteam" Yeoman generator
@@ -14,7 +14,7 @@
 
 set -euo pipefail
 
-USAGE="How to use ./run v3.4.1
+USAGE="How to use ./run v3.4.2
 ===
 
   $ ./run \\
@@ -31,6 +31,8 @@ Commands
 - watch [-s|--watch-site]: Run \`yarn run watch\` (for jekyll sites, watch for changes with \`--watch-site\`)
 - build: Run \`yarn run build\`
 - test: Run \`yarn run test\`
+- test-python: Run \`yarn run test-python\`
+- lint-python: Run \`yarn run lint-python\`
 - stop: Stop any running containers
 - exec [-r|--root] [-p|--expose-port PORT] <args>: Run a command in the development container (optionally exposing a port to the host)
 - yarn [-r|--root] [-p|--expose-port PORT] <script-name>: Run a yarn script from package.json
@@ -43,7 +45,7 @@ Commands
 ##
 
 # Define docker images versions
-dev_image="canonicalwebteam/dev:v1.6.4"
+dev_image="canonicalwebteam/dev:v1.6.7"
 if [ -n "${DOCKER_REGISTRY:-}" ]; then
     dev_image="${DOCKER_REGISTRY}/${dev_image}"
 fi
@@ -156,7 +158,7 @@ while [[ -n "${1:-}" ]] && [[ "${1:0:1}" == "-" ]]; do
             shift
         ;;
         -h|--help) echo "$USAGE"; exit ;;
-        -v|--version) echo "Generated from generator-canonical-webteam@3.4.1"; exit ;;
+        -v|--version) echo "Generated from generator-canonical-webteam@3.4.2"; exit ;;
         *) invalid "Option '${key}' not recognised." ;;
     esac
     shift
@@ -467,6 +469,48 @@ case $run_command in
         else
             echo "==="
             echo "Tests succeeded"
+            echo "==="
+        fi
+    ;;
+    "test-python")
+        update_dependencies
+
+        test_error=false
+
+        # Run node tests
+        echo "- Running python tests"
+        run_as_user "" yarn run test-python || test_error=true
+
+        # Report success or failure
+        if ${test_error}; then
+            echo "==="
+            echo "Tests failed"
+            echo "==="
+            exit 1
+        else
+            echo "==="
+            echo "Tests succeeded"
+            echo "==="
+        fi
+    ;;
+    "lint-python")
+        update_dependencies
+
+        lint_error=false
+
+        # Run node tests
+        echo "- Running python lint"
+        run_as_user "" yarn run lint-python || lint_error=true
+
+        # Report success or failure
+        if ${lint_error}; then
+            echo "==="
+            echo "Lint failed"
+            echo "==="
+            exit 1
+        else
+            echo "==="
+            echo "Lint succeeded"
             echo "==="
         fi
     ;;
